Dalvik Bytecode deocding (missing some instructions)
SUPERAndroidAnalyzer/dalvik pull request #7
Opened 2017-06-03 10:51 UTC by gnieto

I've implemented most of the Dalvik operations (there are some instructions missing: _binop/lit16_, _ binop/lit8_, _invoke-polymorphic_, _invoke-polymorphic/range_, _invoke-custom_, _invoke-custom/range_).

I've created a `ByteCodeDecoder` which is an iterator that yeilds `ByteCode` from the source.

This is not used anywhere else (yet), as the code segments are not yet parsed on develop.

2017-06-03 11:20 UTC, Razican requested changes
Incredible work!! Thanks!

Seems that tests are failing due to formatting. Could you check it? Also, seems we have a lot of warnings from missing docs. Maybe it's not so important right now, but it will be in the future. Let me know what you think.

2017-06-03 13:41 UTC, gnieto commented
I've added the allow missing docs on the bytecodes structures/enums as it will not add any value at the moment (if you are using this, probably you are also looking into dalvik documentation, as it will be a nicer source of data).

Besides this, formatting is ok now and I've added some new documentation.

2017-06-03 15:36 UTC, Razican commented on src/lib.rs
> +    fn from(_: DexReader) -> Dex {
Actually, I like this warning, since it remembers what it's still not implemented.

2017-06-05 19:56 UTC, gnieto commented
Added missing instructions

2017-06-07 07:15 UTC, Razican approved these changes

2017-06-07 07:15 UTC, Razican commented
Amazing work!!! 🎉

2017-06-07 07:16 UTC, merged